import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Card, CardContent, Grid, Chip, CircularProgress,
  Alert, Paper, List, ListItem, ListItemIcon, ListItemText, Divider
} from '@mui/material';
import QuizIcon from '@mui/icons-material/Quiz';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import TopicIcon from '@mui/icons-material/Topic';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';
import axios from 'axios';

const AutoExamStats = () => {
  const [stats, setStats] = useState({
    totalTemplates: 0,
    totalTopics: 0,
    totalExams: 0,
    autoGeneratedExams: 0,
    categories: {},
    recentTopics: [],
    recentExams: []
  });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadStats();
  }, []);

  const loadStats = async () => {
    try {
      setLoading(true);
      setError(null);
      
      // Configurar el token de autenticación
      const token = localStorage.getItem('auth_token') || localStorage.getItem('token');
      const headers = token ? { Authorization: `Bearer ${token}` } : {};
      
      // Intentar cargar datos con manejo de errores individual
      let templates = [];
      let topics = [];
      let exams = [];

      try {
        const templatesResponse = await axios.get('http://:8000/api/topic-templates/stats', { headers });
        templates = templatesResponse.data?.data || [];
      } catch (err) {
        console.warn('Error loading templates:', err);
      }

      try {
        const topicsResponse = await axios.get('http://localhost:8000/api/topics', { headers });
        topics = topicsResponse.data?.data || [];
      } catch (err) {
        console.warn('Error loading topics:', err);
      }

      try {
        const examsResponse = await axios.get('http://localhost:8000/api/exams', { headers });
        exams = examsResponse.data?.data || [];
      } catch (err) {
        console.warn('Error loading exams:', err);
      }

      // Calcular estadísticas
      const statsData = {
        totalTemplates: templates.length || 0,
        totalTopics: topics.length || 0,
        totalExams: exams.length || 0,
        autoGeneratedExams: exams.filter(exam => exam.descripcion?.includes('generado automáticamente')).length || 0,
        categories: templates.reduce((acc, template) => {
          if (template.categoria) {
            acc[template.categoria] = (acc[template.categoria] || 0) + 1;
          }
          return acc;
        }, {}),
        recentTopics: topics.slice(-5).reverse() || [],
        recentExams: exams.slice(-5).reverse() || []
      };

      setStats(statsData);
    } catch (err) {
      console.error('Error loading stats:', err);
      setError('No se pudieron cargar las estadísticas. Mostrando datos por defecto.');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '50vh' }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={{ background: '#f5f7fa', borderRadius: 3, p: 3 }}>
      <Typography variant="h5" sx={{ color: '#1976d2', fontWeight: 700, mb: 3 }}>
        📊 Estadísticas del Sistema de Generación Automática
      </Typography>

      {error && (
        <Alert severity="warning" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {/* Tarjetas de estadísticas principales */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid item xs={12} sm={6} md={3}>
          <Card sx={{ background: 'linear-gradient(135deg, #4caf50 0%, #66bb6a 100%)', color: 'white' }}>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <Box>
                  <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
                    {stats.totalTemplates}
                  </Typography>
                  <Typography variant="body2">
                    Plantillas Disponibles
                  </Typography>
                </Box>
                <AutoAwesomeIcon sx={{ fontSize: 40, opacity: 0.8 }} />
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card sx={{ background: 'linear-gradient(135deg, #2196f3 0%, #42a5f5 100%)', color: 'white' }}>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <Box>
                  <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
                    {stats.totalTopics}
                  </Typography>
                  <Typography variant="body2">
                    Temas Creados
                  </Typography>
                </Box>
                <TopicIcon sx={{ fontSize: 40, opacity: 0.8 }} />
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card sx={{ background: 'linear-gradient(135deg, #ff9800 0%, #ffb74d 100%)', color: 'white' }}>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <Box>
                  <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
                    {stats.totalExams}
                  </Typography>
                  <Typography variant="body2">
                    Exámenes Totales
                  </Typography>
                </Box>
                <QuizIcon sx={{ fontSize: 40, opacity: 0.8 }} />
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card sx={{ background: 'linear-gradient(135deg, #9c27b0 0%, #ba68c8 100%)', color: 'white' }}>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <Box>
                  <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
                    {stats.autoGeneratedExams}
                  </Typography>
                  <Typography variant="body2">
                    Generados Automáticamente
                  </Typography>
                </Box>
                <TrendingUpIcon sx={{ fontSize: 40, opacity: 0.8 }} />
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Categorías de plantillas */}
      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3, borderRadius: 3 }}>
            <Typography variant="h6" sx={{ color: '#1976d2', mb: 2 }}>
              📁 Plantillas por Categoría
            </Typography>
            <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
              {stats.categories && Object.keys(stats.categories).length > 0 ? (
                Object.entries(stats.categories).map(([category, count]) => (
                  <Chip
                    key={category}
                    label={`${category.toUpperCase()}: ${count}`}
                    color="primary"
                    variant="outlined"
                    sx={{ mb: 1 }}
                  />
                ))
              ) : (
                <Typography variant="body2" color="textSecondary">
                  No hay categorías disponibles
                </Typography>
              )}
            </Box>
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3, borderRadius: 3 }}>
            <Typography variant="h6" sx={{ color: '#1976d2', mb: 2 }}>
              📈 Eficiencia del Sistema
            </Typography>
            <Box>
              <Typography variant="body2" sx={{ mb: 1 }}>
                <strong>Tasa de Generación Automática:</strong>
              </Typography>
              <Typography variant="h4" color="primary" sx={{ fontWeight: 'bold' }}>
                {stats.totalExams > 0 
                  ? Math.round((stats.autoGeneratedExams / stats.totalExams) * 100)
                  : 0}%
              </Typography>
              <Typography variant="body2" color="textSecondary">
                {stats.autoGeneratedExams} de {stats.totalExams} exámenes generados automáticamente
              </Typography>
            </Box>
          </Paper>
        </Grid>
      </Grid>

      {/* Temas y exámenes recientes */}
      <Grid container spacing={3} sx={{ mt: 2 }}>
        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3, borderRadius: 3 }}>
            <Typography variant="h6" sx={{ color: '#1976d2', mb: 2 }}>
              🆕 Temas Recientes
            </Typography>
            <List>
              {stats.recentTopics && stats.recentTopics.length > 0 ? (
                stats.recentTopics.map((topic, index) => (
                  <Box key={topic.id || index}>
                    <ListItem>
                      <ListItemIcon>
                        <CheckCircleIcon color="primary" />
                      </ListItemIcon>
                      <ListItemText
                        primary={topic.nombre || 'Tema sin nombre'}
                        secondary={`Materia: ${topic.subject?.nombre || 'N/A'}`}
                      />
                    </ListItem>
                    {index < stats.recentTopics.length - 1 && <Divider />}
                  </Box>
                ))
              ) : (
                <Typography variant="body2" color="textSecondary" sx={{ p: 2 }}>
                  No hay temas recientes
                </Typography>
              )}
            </List>
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3, borderRadius: 3 }}>
            <Typography variant="h6" sx={{ color: '#1976d2', mb: 2 }}>
              📝 Exámenes Recientes
            </Typography>
            <List>
              {stats.recentExams && stats.recentExams.length > 0 ? (
                stats.recentExams.map((exam, index) => (
                  <Box key={exam.id || index}>
                    <ListItem>
                      <ListItemIcon>
                        <QuizIcon color="secondary" />
                      </ListItemIcon>
                      <ListItemText
                        primary={exam.titulo || 'Examen sin título'}
                        secondary={`${exam.questions?.length || 0} preguntas • ${exam.duracion_minutos || 0} min`}
                      />
                    </ListItem>
                    {index < stats.recentExams.length - 1 && <Divider />}
                  </Box>
                ))
              ) : (
                <Typography variant="body2" color="textSecondary" sx={{ p: 2 }}>
                  No hay exámenes recientes
                </Typography>
              )}
            </List>
          </Paper>
        </Grid>
      </Grid>
    </Box>
  );
};

export default AutoExamStats; 